name = "turbocache"
workers_dev = true
compatibility_date = "2021-12-24"
compatibility_flags = []

[[r2_buckets]]
binding = 'R2_BUCKET' 
bucket_name = 'turbocache-artifacts'

[build]
command = "yarn esbuild src/worker.ts --bundle --outfile=dist/worker.js --format=esm"

[triggers]
crons = ["0 0 * * *"]